"""Package the roster agent as a single Windows .exe for moderators.

    python build_agent.py --server https://vrcmod.example.cc

Produces dist/VRChatRosterAgent.exe with the server URL compiled in, so a
moderator downloads one file and double-clicks it. Nothing to install — no
Python, no Vosk, no audio libraries.

**No credential is baked in by default.** On first run the agent prints a link,
a moderator opens it in the panel, and the server hands that PC its own key.
Anyone holding the .exe can pull strings out of it, so the less that is in
there, the better: a leaked build is then worth nothing at all.

`--token` still bakes one in for the old behaviour. If you use it, use the
server's `roster_token` and never `sync_token` — the value inside must only be
able to report who is in an instance, not read incidents or age checks.
"""

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
BAKED = HERE / "agent_baked.py"
NAME = "VRChatRosterAgent"


def write_baked(server: str, token: str) -> None:
    BAKED.write_text(
        '"""Generated by build_agent.py — do not edit or commit."""\n'
        f"SERVER = {server.rstrip('/')!r}\n"
        f"TOKEN = {token!r}\n",
        encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--server", required=True,
                    help="e.g. https://vrcmod.example.cc")
    ap.add_argument("--token", default="",
                    help="optional: bake in the server's roster_token (NOT "
                         "sync_token). Omit, and the agent pairs on first run")
    ap.add_argument("--keep-baked", action="store_true",
                    help="leave agent_baked.py behind for inspection")
    args = ap.parse_args()

    if not args.server.startswith(("http://", "https://")):
        ap.error("--server must include the scheme, e.g. https://…")

    if args.token:
        print(f"Baking in {args.server}  "
              f"(token {args.token[:4]}…{args.token[-4:]})")
    else:
        print(f"Baking in {args.server}  (no token — pairs on first run)")
    write_baked(args.server, args.token)
    try:
        cmd = [
            sys.executable, "-m", "PyInstaller",
            "--onefile", "--console", "--clean", "--noconfirm",
            "--name", NAME,
            # agent_baked is imported in a try/except, so PyInstaller's static
            # analysis does not see it; say so explicitly.
            "--hidden-import", "agent_baked",
            "--paths", str(HERE),
            str(HERE / "agent.py"),
        ]
        print("  " + " ".join(cmd[1:]))
        result = subprocess.run(cmd, cwd=HERE)
        if result.returncode != 0:
            return result.returncode
    finally:
        if not args.keep_baked:
            BAKED.unlink(missing_ok=True)
            shutil.rmtree(HERE / "__pycache__", ignore_errors=True)

    exe = HERE / "dist" / f"{NAME}.exe"
    if not exe.exists():
        print("build reported success but no exe was produced", file=sys.stderr)
        return 1
    print(f"\nBuilt {exe}  ({exe.stat().st_size / 1e6:.1f} MB)")
    print("Hand this to a moderator who is in the instance; they double-click "
          "it and leave it running.")
    if not args.token:
        print("On first run it prints a link for them to open in the panel, "
              "and is handed its own key.")
    print("Windows SmartScreen will warn on first run because the binary is "
          "unsigned — 'More info' then 'Run anyway'.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
